#!/bin/bash

# usage:
# bash open_port 172.16.7.7:22 raf@hub.rafael.nz:10022
#
# connects to hub@rafael.nz via ssh and 
# open the port 10022 on hub.rafael.nz 
# and forwards it to 172.16.7.7:22

TARGET=$1
DESTINATION=$2

FORWARDED_HOST=$(cut -f1 -d: <(echo $TARGET))
FORWARDED_PORT=$(cut -f2 -d: <(echo $TARGET))

SSH_HOST=$(cut -f1 -d: <(echo $DESTINATION))
SSH_OPENED_PORT=$(cut -f2 -d: <(echo $DESTINATION))

ssh -fnNT -R ${SSH_OPENED_PORT}:${FORWARDED_PORT} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${SSH_HOST}
PID=$!
STATUS=$([ $? -eq 0 ] && echo 'success' || echo 'failed')
echo "${STATUS} opening port ${SSH_OPENED_PORT} on ${SSH_HOST} forwarding to ${TARGET} (pid: ${PID})"

