#!/bin/bash

# usage:
#  bash redirect_port [from_host|from_ip]:<from_port> <to_host|to_ip>:<to_port> <on_connection>
#
# example:
# bash redirect_port 0.0.0.0:10022 172.16.7.7:22 raf@hub.rafael.nz
#
# connects to hub@rafael.nz via ssh and 
# open the port 0.0.0.0:10022 on hub.rafael.nz 
# and forwards it to (redirect connections to it to) 172.16.7.7:22

FROM_PORT=$1
TO_PORT=$2
ON_HOST=$3

OPENED_PORT=$(cut -f2 -d: <(echo $FROM_PORT))

ssh -fnNT -R ${FROM_PORT}:${TO_PORT} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey ${ON_HOST} &
PID=$!
echo "forwarding connections on ${ON_HOST}:${OPENED_PORT} to ${TO_PORT}. (PID: $PID)"

